update pnpm lock

diff --git a/Dockerfile.prod b/Dockerfile.prod
--- a/Dockerfile.prod
+++ b/Dockerfile.prod
@@ -15,6 +15,8 @@ COPY . .
 
 RUN npx prisma generate
 RUN ls node_modules/.pnpm | grep prisma 
+RUN ls node_modules/.pnpm | grep client-runtime-utils || echo "NOT FOUND"
+
 RUN pnpm build
 
 
